In [254]:
import numpy as np
import pandas as pd
from nltk import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
import random

In [255]:
"""
Turkish Cyberbullying veri seti, içerisinde kötü kelimeler bulunan ve bulunmayan metinler olmak üzere 
3000 adet twitter verisinden oluşmaktadır.Amacım bu veri setini kullanarak Türkçe Nlp çalışması yapıp 
yeni bir metnin içerisinde küfür,argo veya kötü bir kelime olup olmadığını kontrol etmektir.
"""

'\nTurkish Cyberbullying veri seti, içerisinde kötü kelimeler bulunan ve bulunmayan metinler olmak üzere \n3000 adet twitter verisinden oluşmaktadır.Amacım bu veri setini kullanarak Türkçe Nlp çalışması yapıp \nyeni bir metnin içerisinde küfür,argo veya kötü bir kelime olup olmadığını kontrol etmektir.\n'

In [256]:
data=pd.read_csv("turkish cyberbullying.csv")

In [257]:
data.head()

message  cyberbullying
0  rabbim kalan ömrünü geçen ömründen hayırlı eyl...              0
1  bir ateist olarak bu resmi gördükçe gözyaşları...              0
2                 oo süpersin azıcık bize de bulaşsa              0
3              bende biliyorum benden bı bok olmicak              1
4                                nerdesin len tirrek              1

In [258]:
data.tail()

message  cyberbullying
2996  bismillahirahmanirahim yaallah hayırlı sabahla...              0
2997                                jskdpdğeff deli amk              1
2998             nasıl bir yavşak serefsizsiniz hepiniz              1
2999                          shipshipshiphayırlı olsun              0
3000                                 çookk tatlısın çok              0

In [259]:
print(type(data))
print(len(data))
data.columns

<class 'pandas.core.frame.DataFrame'>
3001


Index(['message', 'cyberbullying'], dtype='object')

In [260]:
X_train=np.array(data["message"]).reshape(-1,1)
Y_train=np.array(data["cyberbullying"]).reshape(-1,1)

In [261]:
X_train.shape

(3001, 1)

In [262]:
Y_train.shape

(3001, 1)

In [263]:
print(X_train[:10])

[['rabbim kalan ömrünü geçen ömründen hayırlı eylesin']
 ['bir ateist olarak bu resmi gördükçe gözyaşlarıma mani olamıyorum']
 ['oo süpersin azıcık bize de bulaşsa']
 ['bende biliyorum benden bı bok olmicak']
 ['nerdesin len tirrek']
 ['dogruyusoyleyince kadro verince adalet yerini bulacak']
 ['ogrenciler hocalarına memleket durusuna hayran ']
 ['gunaydin hala yatakta olanlar eminim elinizde telefon aletinizde tad gibidir hadi sanalda sabah keyfi yapalim']
 ['artist pezevenk takimi yakti rezildi']
 ['ve o narinlikte ve sevimlilikte cüce öylesine acımasızca zibh eğliyip']]


In [264]:
print(Y_train[:10])

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]]


In [265]:
stop_words = list(stopwords.words('turkish'))

In [266]:
print(stop_words)
print("-------------",len(stop_words),"adet tek başına herhangi bir anlamı olmayan kelime bulunmaktadır.---------------------")

['acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani']
------------- 53 adet tek başına herhangi bir anlamı olmayan kelime bulunmaktadır.---------------------


In [267]:
#Data preprocessing

def data_prep_stop_words(text):
    text = text.lower()
    wordlist = text.split()
    clean_text=[]
    words_list=[w for w in wordlist if w not in stop_words]
    return " ".join(words_list)


In [268]:
clean_messages=[]
for message in data["message"]:
    clean_messages.append(data_prep_stop_words(message))


In [269]:
clean_messages[0:10]

['rabbim kalan ömrünü geçen ömründen hayırlı eylesin',
 'bir ateist olarak resmi gördükçe gözyaşlarıma mani olamıyorum',
 'oo süpersin azıcık bize bulaşsa',
 'bende biliyorum benden bı bok olmicak',
 'nerdesin len tirrek',
 'dogruyusoyleyince kadro verince adalet yerini bulacak',
 'ogrenciler hocalarına memleket durusuna hayran',
 'gunaydin hala yatakta olanlar eminim elinizde telefon aletinizde tad gibidir hadi sanalda sabah keyfi yapalim',
 'artist pezevenk takimi yakti rezildi',
 'narinlikte sevimlilikte cüce öylesine acımasızca zibh eğliyip']

In [270]:
x_train,x_test,y_train,y_test=train_test_split(clean_messages,Y_train,test_size=0.25,random_state=42)
x_train=np.array(x_train)
x_test=np.array(x_test)
y_train=np.array(y_train)
y_test=np.array(y_test)

In [271]:
print("x_train infos : len=>",x_train.shape)
print("y_train infos : len=>",len(y_train))
print("x_test infos : len=>",len(x_test))
print("y_test infos : len=>",len(y_test))

x_train infos : len=> (2250,)
y_train infos : len=> 2250
x_test infos : len=> 751
y_test infos : len=> 751


In [272]:
x = data.message.values
veri=x.copy()
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=5,stop_words=stop_words,ngram_range=(1,3))
vectorizer.fit(veri)

BoW = vectorizer.transform(veri)
repr(BoW)

"<3001x795 sparse matrix of type '<class 'numpy.int64'>'\n\twith 11001 stored elements in Compressed Sparse Row format>"

In [297]:
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer

In [298]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score

In [313]:
from sklearn.pipeline import Pipeline

In [300]:
x_train.shape

(2250,)

In [316]:
from sklearn.feature_extraction.text import TfidfVectorizer
for min_df in [1,2,3,4,5,6]:
    for n_gram in [(1,1),(1,2),(1,3),(2,3)]:
        tf_vectorizer = TfidfVectorizer(min_df=min_df, stop_words=stop_words,ngram_range=n_gram)
        veri1 = tf_vectorizer.fit_transform(veri)
        best = veri1.max(axis=0).toarray().ravel()
        sort_by_tfidf = best.argsort()
        feature_names = np.array(tf_vectorizer.get_feature_names())
        print("Vocabularies using min_df={} and n_gram={} with highest tfidf: \n{}".format(min_df, n_gram, feature_names[sort_by_tfidf[-20:]]))
        print("The number of vocabularies: {}".format(len(tf_vectorizer.vocabulary_)))
        sort_by_tfidf = np.argsort(tf_vectorizer.idf_)
        print("Vocabularies with lowest idf:\n{}".format(feature_names[sort_by_tfidf[:20]]))
        print('-----------------------------------')

Vocabularies using min_df=1 and n_gram=(1, 1) with highest tfidf: 
['sınav' 'uzat' 'gittin' 'sıffır' 'hödük' 'vay' 'tarzdır' 'hee' 'yalayın'
 'styling' 'güzelsin' 'tatlısın' 'tırrek' 'andaval' 'sisko' 'şişko'
 '09052018' 'diyarbakır' 'tatlı' 'yobaz']
The number of vocabularies: 11458
Vocabularies with lowest idf:
['bir' 'sen' 'kadar' 'ben' 'var' 'bi' 'senin' 'orospu' 'amk' 'seni'
 'olsun' 'lan' 'gerizeka' 'mutluyum' 'yok' 'pislik' 'mi' 'güzel' 'andaval'
 'değil']
-----------------------------------
Vocabularies using min_df=1 and n_gram=(1, 2) with highest tfidf: 
['güzelsin kız' 'güzelsin çocuk' 'herkes gerizeka' 'uzat' 'güzelsin sen'
 'güzelsin güzel' 'ulan amk' 'hee' 'yalayın' 'diyarbakır' 'andaval'
 'sisko' 'tırrek' 'tatlısın' '09052018' 'styling' 'yobaz' 'tatlı' 'şişko'
 'güzelsin']
The number of vocabularies: 32321
Vocabularies with lowest idf:
['bir' 'sen' 'ben' 'kadar' 'var' 'bi' 'senin' 'orospu' 'amk' 'seni'
 'olsun' 'lan' 'gerizeka' 'mutluyum' 'yok' 'pislik' 'mi' 'güzel' 'and

Vocabularies using min_df=5 and n_gram=(1, 1) with highest tfidf: 
['kız' 'kültür' 'kutlu' 'kitap' 'kerhane' 'kendi' 'keko' 'kaybetmekorkusu'
 'ilkbahar' 'karşı' 'kaldı' 'kahpe' 'kadın' 'kadro' 'kadar' 'iyi'
 'istiyorum' 'insanlar' 'kardeşim' 'şırfıntı']
The number of vocabularies: 759
Vocabularies with lowest idf:
['bir' 'sen' 'ben' 'kadar' 'var' 'bi' 'senin' 'orospu' 'amk' 'seni'
 'olsun' 'lan' 'gerizeka' 'mutluyum' 'yok' 'pislik' 'mi' 'güzel' 'andaval'
 'değil']
-----------------------------------
Vocabularies using min_df=5 and n_gram=(1, 2) with highest tfidf: 
['dallama' 'cüce' 'sinema' 'cok' 'böyle' 'gerzek' 'sizin' 'cidden'
 'cibiliyetsiz' 'sokarım' 'guzel' 'son' 'sonra' 'cerrahpaşaduruşu'
 'cenabet' 'göt' 'bütün' 'bücür' 'gurur' 'şırfıntı']
The number of vocabularies: 793
Vocabularies with lowest idf:
['bir' 'sen' 'ben' 'kadar' 'var' 'bi' 'senin' 'orospu' 'amk' 'seni'
 'olsun' 'lan' 'gerizeka' 'mutluyum' 'yok' 'mi' 'pislik' 'güzel' 'andaval'
 'değil']
-------------------------

In [317]:
LinearSVC_tfidf = Pipeline([
        ('tfidfvectorizer', TfidfVectorizer()),
        ('LinearSVC', LinearSVC(max_iter=1000))
])
Naive_tfidf = Pipeline([
        ('tfidfvectorizer', TfidfVectorizer()),
        ('multinomialnb', MultinomialNB())
])
Decision_tfidf = Pipeline([
        ('tfidfvectorizer', TfidfVectorizer()),
        ('decisiontreeclassifier', DecisionTreeClassifier())
])
RandomForest_tfidf = Pipeline([
        ('tfidfvectorizer', TfidfVectorizer()),
        ('randomforestclassifier', RandomForestClassifier(n_estimators=100))
])

In [318]:
parameters_of_svc_tfidf = [ 
    {
        'LinearSVC__C': [0.01, 0.1, 1, 10, 100], 
        'tfidfvectorizer__min_df': [1,3,5], 
        'tfidfvectorizer__stop_words': [stop_words],
        'tfidfvectorizer__ngram_range': [(1, 1), (1, 2), (1, 3), (2, 3)]
    } 
]

parameters_of_general_tfidf = [ 
    {
        'tfidfvectorizer__min_df': [1,3,5], 
        'tfidfvectorizer__stop_words': [stop_words],
        'tfidfvectorizer__ngram_range': [(1, 1), (1, 2), (1, 3), (2, 3)]
    }
]

In [319]:
for models, parameters, name in zip([LinearSVC_tfidf, Naive_tfidf, Decision_tfidf, RandomForest_tfidf],
                                    [parameters_of_svc_tfidf, parameters_of_general_tfidf, parameters_of_general_tfidf, parameters_of_general_tfidf],
                                    ["LinearSVC","Multinomial Naive Bayes","Decision Tree","Random Forest"]):

    grid = GridSearchCV(models, parameters, cv=5)
    grid.fit(x_train, y_train)
    print("Model ismi: "+ name)
    print("En iyi cross-validation score: {:.2f}".format(grid.best_score_ * 100))
    print("En iyi parametreler: ", grid.best_params_)
    
    y_train_pred = grid.predict(x_train)
    print(confusion_matrix(y_train, y_train_pred))
    
    final_model = grid.best_estimator_
    final_test_prediction = final_model.score(x_test, y_test)
    print("Test score: {:.2f}%".format(final_test_prediction * 100))    
    print("--------------------------")

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Model ismi: LinearSVC
En iyi cross-validation score: 88.44
En iyi parametreler:  {'LinearSVC__C': 10, 'tfidfvectorizer__min_df': 1, 'tfidfvectorizer__ngram_range': (1, 2), 'tfidfvectorizer__stop_words': ['acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani']}
[[1118    0]
 [   0 1132]]
Test score: 90.15%
--------------------------


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

Model ismi: Multinomial Naive Bayes
En iyi cross-validation score: 86.18
En iyi parametreler:  {'tfidfvectorizer__min_df': 1, 'tfidfvectorizer__ngram_range': (1, 3), 'tfidfvectorizer__stop_words': ['acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani']}
[[1118    0]
 [   0 1132]]
Test score: 86.95%
--------------------------
Model ismi: Decision Tree
En iyi cross-validation score: 83.78
En iyi parametreler:  {'tfidfvectorizer__min_df': 1, 'tfidfvectorizer__ngram_range': (1, 3), 'tfidfvectorizer__stop_words': ['acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diy

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n

Model ismi: Random Forest
En iyi cross-validation score: 85.60
En iyi parametreler:  {'tfidfvectorizer__min_df': 3, 'tfidfvectorizer__ngram_range': (1, 1), 'tfidfvectorizer__stop_words': ['acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani']}
[[1116    2]
 [  15 1117]]
Test score: 86.42%
--------------------------


In [320]:
best_pipeline = Pipeline([
    ('tfidfvectorizer', TfidfVectorizer(min_df=1,stop_words=stop_words,ngram_range=(1,2)))
 
])

In [321]:
best_pipeline.fit(x_train,y_train)

Pipeline(memory=None,
     steps=[('tfidfvectorizer', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 2), norm='l2', preprocessor=None, smooth...
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None))])

In [322]:
best_pipeline.steps

[('tfidfvectorizer',
  TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
          dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
          lowercase=True, max_df=1.0, max_features=None, min_df=1,
          ngram_range=(1, 2), norm='l2', preprocessor=None, smooth_idf=True,
          stop_words=['acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani'],
          strip_accents=None, sublinear_tf=False,
          token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
          vocabulary=None))]

In [323]:
final_test_prediction = best_pipeline.score(x_test,y_test)
print("Final test score:",final_test_prediction)

y_test_pred = best_pipeline.predict(x_test)
print("Confusion matrix\n",confusion_matrix(y_test,y_test_pred))

AttributeError: 'TfidfVectorizer' object has no attribute 'score'